default: !inherit
  parent: ".base"

  steps:
    conform:
      label: "Conform"
      index: 40
      commands:
        copy:
          label: "Copy file to pipeline"
          path: "silex_client.commands.copy.Copy"
          parameters:
            src:
              value: !command-output "input:input:file_paths"
              hide: true
            dst:
              value: !command-output "get_conform_location:build_output_path:directory"
              hide: true
        rename:
          label: "Rename the copied files"
          path: "silex_client.commands.rename.Rename"
          parameters:
            src:
              value: !command-output "conform:copy:destination_paths"
              hide: true
            name:
              value: !command-output "get_conform_location:check_existing_files:file_paths"
              hide: true
            force: false
