default:
  steps:
    input:
      hide: true
      index: 10
      commands:
        input:
          path: "silex_client.commands.pass.Pass"

    conform:
      label: "Conform"
      index: 20
      commands:
        get_conform_cache:
          label: "Get previous conform location"
          path: "silex_client.commands.get_stored_value.GetStoredValue"
          parameters:
            key: "build_output_path_task_id"
            key_suffix: !command-output "input:input:file_paths"
          hide: true
        get_fast_conform_cache:
          label: "Check fast conform"
          path: "silex_client.commands.get_stored_value.GetStoredValue"
          parameters:
            key: "fast_conform_enabled"
            key_suffix: !command-output "input:input:file_paths"
            default: false
          hide: true
        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path_conform.BuildOutputPathConform"
          tooltip: "Build the complete output path"
          parameters:
            task: !command-output "conform:get_conform_cache:value"
            fast_conform: !command-output "conform:get_fast_conform_cache:value"
            use_current_context: false
            create_temp_dir: false
            frame_set: !command-output "input:input:frame_set"
            output_type:
              hide: true
            files: !command-output "input:input:file_paths"
            padding: !command-output "input:input:padding"
          ask_user: true
        set_conform_cache:
          label: "Cache conform location"
          path: "silex_client.commands.set_stored_value.SetStoredValue"
          parameters:
            key: "build_output_path_task_id"
            key_suffix: !command-output "input:input:file_paths"
            value: !command-output "conform:build_output_path:task"
          hide: true
        set_fast_conform_cache:
          label: "Cache conform location"
          path: "silex_client.commands.set_stored_value.SetStoredValue"
          parameters:
            key: "fast_conform_enabled"
            key_suffix: !command-output "input:input:file_paths"
            value: !command-output "conform:build_output_path:fast_conform"
          hide: true
        copy:
          label: "Copy file to pipeline"
          path: "silex_client.commands.copy.Copy"
          parameters:
            src: 
              value: !command-output "input:input:file_paths"
              hide: true
            dst: 
              value: !command-output "conform:build_output_path:directory"
              hide: true
            force: false
        rename:
          label: "Rename the copied files"
          path: "silex_client.commands.rename.Rename"
          parameters:
            src: 
              value: !command-output "conform:copy:destination_paths"
              hide: true
            name: 
              value: !command-output "conform:build_output_path:full_name"
              hide: true
            force: false

    output:
      index: 30
      hide: true
      commands:
        output:
          path: "silex_client.commands.pass.Pass"
          parameters:
            input: !command-output "conform:rename:new_paths"
