gif: !inherit
  parent: ".default"

  steps:
    conform:
      commands:
        build_output_path:
          parameters:
            output_type:
              value: "gif"
    silex_coins:
      index: 500
      hide: true
      commands:
        add_silex_coins:
          path: "silex_client.commands.user.silex_coins.AddSilexCoinsCommand"
          parameters:
            amount:
              value: 50

    