tiff:
  steps:
    input:
      hide: true
      index: 10
      commands:
        input:
          path: "silex_client.commands.pass.Pass"

    conform:
      label: "Conform"
      index: 20
      commands:
        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          tooltip: "Build the complete output path"
          parameters:
            output_type: "tiff"
          ask_user: true
        copy:
          label: "Copy file to pipeline"
          path: "silex_client.commands.copy.Copy"
          ask_user: True
          parameters:
            source_path: !command-output "input:input"
            destination_dir: !command-output "conform:build_output_path:directory"
            override: false

    output:
      index: 30
      commands:
        output:
          path: "silex_client.commands.pass.Pass"
          parameters:
            input: !command-output "conform:copy:destination_path"
