arnold_3D4:
  label: "Submit ass sequence"
  steps:
    send_kick_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_kick_cmd:
          path: "silex_client.commands.build_kick_cmd.KickCommand"
          label: "arnold Job parameters"
          ask_user: true
          parameters:
            directory:
              hide: true
            export_name:
              hide: true
            extension:
              hide: true

        submit_to_tractor:
          label: "Submit"
          path: "silex_client.commands.submit_to_tractor.TractorSubmiter"
          ask_user: true
          parameters:
            cmd_dict:
              value: !command-output "send_kick_render:build_kick_cmd:commands"
              hide: true
            job_title:
              value: !command-output "send_kick_render:build_kick_cmd:file_name"
              hide: true
