arnold_3D4:
  label: "Submit ass sequence"
  steps:
    send_kick_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_kick_cmd:
          path: "silex_client.commands.build_kick_cmd.KickCommand"
          label: "Arnold job parameters"
          ask_user: true

        submit_to_tractor:
          label: "Submit"
          path: "silex_client.commands.submit_to_tractor.TractorSubmiter"
          ask_user: true
          parameters:
            job_title:
              value: !command-output "send_kick_render:build_kick_cmd:file_name"
            commands:
              value: !command-output "send_kick_render:build_kick_cmd:commands"
