arnold:
  label: "Submit ass sequence"
  steps:
    build_output_path:
      label: "Build output path"
      index: 10
      commands:
        select_list:
          label: "Enter extension"
          path: "silex_client.commands.select_list.SelectList"
          parameters:
            parameters_list:
              - "exr"
              - "png"
              - "jpg"
              - "tiff"
            param_name: "Render type"

        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          tooltip: "Build the complete output path"
          ask_user: true
          parameters:
            output_type: !command-output "build_output_path:select_list"
            create_temp_dir: false
            create_output_dir: true
            task:
              hide: true
            use_current_context:
              value: true
              hide: true
            frame_set:
              hide: true
            name:
              value: "render"

    send_kick_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_kick_cmd:
          path: "silex_client.commands.build_kick_cmd.KickCommand"
          label: "arnold Job parameters"
          ask_user: true
          parameters:
            directory: !command-output "build_output_path:build_output_path:directory"
            export_name: !command-output "build_output_path:build_output_path:file_name"
            extension: !command-output "build_output_path:select_list"

        submit_to_tractor:
          label: "Submit"
          path: "silex_client.commands.submit_to_tractor.TractorSubmiter"
          ask_user: true
          parameters:
            precommands:
              hide: true
            cmd_dict: !command-output "send_kick_render:build_kick_cmd:commands"
            job_title: !command-output "send_kick_render:build_kick_cmd:file_name"
