houdini_redshift: !inherit
  parent: ".houdini"
  label: "Submit Houdini Redshift scene"

  steps:
    redshift_license:
      index: 15
      hide: true
      commands:
        build_redshift_license_cmd:
          path: "silex_client.commands.farm.build_redshift_license_cmd.RedshiftLicenseCommand"

    houdini_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_houdini_tasks:
          label: "Houdini Redshift job parameters"
          parameters:
            pre_command:
              value: !command-output "redshift_license:build_redshift_license_cmd:pre_command"
            cleanup_command:
              value: !command-output "redshift_license:build_redshift_license_cmd:cleanup_command"

        submit_to_tractor:
          label: "Submit"
          path: "silex_client.commands.farm.submit_to_tractor.SubmitToTractorCommand"
          ask_user: true
          parameters:
            job_tags:
              value:
                - "houdini"
                - "redshift"
            job_title:
              value: !command-output "houdini_render:build_houdini_tasks:file_name"
            tasks:
              value: !command-output "houdini_render:build_houdini_tasks:tasks"
            blade_and_filters:
              value:
                - "REDSHIFT"
