houdini:
  label: "Submit houdini"
  steps:
    build_output_path:
      label: "Build render path"
      index: 10
      commands:
        select_extension:
          label: "Output extension"
          path: "silex_client.commands.select_list.SelectList"
          parameters:
            parameters_list:
              - "exr"
              - "png"
              - "jpg"
              - "tiff"
              - "usd"
              - "bgeo"
            param_name: "Render type"

        build_output_path:
          label: "Build render path"
          path: "silex_client.commands.build_render_path.BuildRenderPath"
          tooltip: "Build the complete output path"
          ask_user: true
          parameters:
            output_type:
              value: !command-output "build_output_path:select_extension"
              hide: true
            create_temp_dir: false
            create_output_dir: true
            task:
              hide: true
            use_current_context:
              value: true
              hide: true
            frame_set:
              hide: true
            name:
              value: "render"

    houdini_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_houdini_tasks:
          path: "silex_client.commands.farm.houdini_render_tasks.HoudiniRenderTasksCommand"
          label: "Houdini job parameters"
          ask_user: true
          parameters:
            output_filename:
              value: !command-output "build_output_path:build_output_path:full_path"

        submit_to_deadline:
          label: "Submit"
          path: "silex_client.commands.farm.submit_to_deadline.SubmitToDeadlineCommand"
          ask_user: true
          parameters:
            jobs:
              value: !command-output "houdini_render:build_houdini_tasks:jobs"
