kick:
  label: "Submit ass sequence"
  steps:
    build_output_path:
      label: "Build output path"
      index: 10
      commands:
        select_list:
          label: "Enter extension"
          path: "silex_client.commands.select_list.SelectList"
          parameters:
            param_name: "Output extension"
            parameters_list:
              - "exr"
              - "png"
              - "jpg"
              - "tiff"

        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          tooltip: "Build the complete output path"
          ask_user: true
          parameters:
            output_type:
              value: !command-output "build_output_path:select_list"
              hide: true
            create_temp_dir: false
            create_output_dir: true
            task:
              hide: true
            use_current_context:
              value: true
              hide: true
            frame_set:
              hide: true
            name:
              value: "render"

    kick_render:
      label: "Setup Kick parameters"
      index: 20
      commands:
        kick_render_tasks:
          path: "silex_client.commands.farm.kick_render_tasks.KickRenderTasksCommand"
          label: "Arnold job parameters"
          ask_user: true
          parameters:
            output_path:
              value: !command-output "build_output_path:build_output_path:full_path"

        submit_to_deadline:
          label: "Submit"
          path: "silex_client.commands.farm.submit_to_deadline.SubmitToDeadlineCommand"
          ask_user: true
          parameters:
            jobs:
              value: !command-output "kick_render:kick_render_tasks:jobs"