maya:
  label: "Submit Maya scene"
  steps:
    build_output_path:
      label: "Build output path"
      index: 10
      commands:
        select_extension:
          label: "Enter extension"
          path: "silex_client.commands.select_list.SelectList"
          parameters:
            param_name: "Output extension"
            parameters_list:
              - "exr"
              - "png"
              - "jpg"
              - "tiff"

        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          tooltip: "Build the complete output path"
          ask_user: true
          parameters:
            output_type:
              value: !command-output "build_output_path:select_extension"
              hide: true
            create_temp_dir: false
            create_output_dir: false
            task:
              hide: true
            use_current_context:
              value: true
              hide: true
            frame_set:
              hide: true
            name:
              value: "render"

    maya_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_maya_tasks:
          path: "silex_client.commands.farm.maya_render_tasks.MayaRenderTasksCommand"
          label: "Maya Job parameters"
          ask_user: true
          parameters:
            output_path:
              value: !command-output "build_output_path:build_output_path:full_path"

        submit_to_deadline:
          label: "Submit"
          path: "silex_client.commands.farm.submit_to_deadline.SubmitToDeadlineCommand"
          ask_user: true
          parameters:
            jobs:
              value: !command-output "maya_render:build_maya_tasks:jobs"