natron:
  label: "Submit Natron scene"
  steps:
    build_output_path:
      label: "Build output path"
      index: 10
      commands:
        select_extension:
          label: "Output extension"
          path: "silex_client.commands.select_list.SelectList"
          parameters:
            param_name: "Output extension"
            parameters_list:
              - "exr"
              - "png"
              - "jpg"
              - "tiff"

        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          ask_user: true
          parameters:
            create_temp_dir: false
            create_output_dir: false
            output_type:
              value: !command-output "build_output_path:select_extension"
              hide: true
            use_current_context:
              value: true
              hide: true
            name:
              value: "render"

    natron_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_natron_tasks:
          path: "silex_client.commands.farm.natron_render_tasks.NatronRenderTasksCommand"
          label: "Natron Job parameters"
          ask_user: true
          parameters:
            output_directory:
              value: !command-output "build_output_path:build_output_path:directory"
            output_filename:
              value: !command-output "build_output_path:build_output_path:file_name"
            output_extension:
              value: !command-output "build_output_path:select_extension"

        submit_to_tractor:
          label: "Submit"
          path: "silex_client.commands.farm.submit_to_tractor.SubmitToTractorCommand"
          ask_user: true
          parameters:
            tasks:
              value: !command-output "natron_render:build_natron_tasks:tasks"
            job_title:
              value: !command-output "natron_render:build_natron_tasks:file_name"
            job_tags:
              value:
                - "natron"
