nuke:
  label: "Submit nuke script"
  steps:
    submit_job:
      label: "Setup render parameters"
      index: 20
      commands:
        build_nuke_tasks:
          path: "silex_client.commands.NukeRenderTasksCommand"
          label: "Nuke Job parameters"
          ask_user: true
          parameters:
            frame_range:
              value: "1001-1050x1"

        submit_to_tractor:
          path: "silex_client.commands.SubmitToTractorCommand"
          ask_user: true
          parameters:
            job_title:
              value: !command-output "submit_job:build_nuke_tasks:file_name"
            tasks:
              value: !command-output "submit_job:build_nuke_tasks:tasks"
