vrscene:
  label: "Submit V-Ray scene"
  steps:
    build_output_path:
      index: 10
      commands:
        select_list:
          label: "Enter extension"
          path: "silex_client.commands.select_list.SelectList"
          parameters:
            parameters_list:
              - "exr"
              - "png"
              - "jpg"
              - "tiff"
            param_name: "Render type"

    send_vray_render:
      label: "Setup render parameters"
      index: 20
      commands:
        build_vray_cmd:
          path: "silex_client.commands.build_vray_cmd.VrayCommand"
          label: "V-Ray Job parameters"
          ask_user: true
          parameters:
            extension: !command-output "build_output_path:select_list"

        submit_to_tractor:
          label: "Submit"
          path: "silex_client.commands.submit_to_tractor.TractorSubmiter"
          ask_user: true
          parameters:
            cmd_list: !command-output "send_vray_render:build_vray_cmd:commands"
            job_title: !command-output "send_vray_render:build_vray_cmd:file_name"
