conform:
  steps:
    setup:
      lavel: "Setup"
      index: 50
      commands:
        get_conform_output:
          label: "Select conform type"
          path: "silex_client.commands.select_conform.SelectConform"
          tooltip: "Select the type of conform you want to make"
          parameters:
            auto_select_type: true

        append_conform_action:
          label: "Append conform action"
          path: "silex_client.commands.insert_action.InsertAction"
          tooltip: "Append the selected conform to the list of commands to execute"
          parameters:
            value: !command-output "setup:get_conform_output"
            action: !command-output "setup:get_conform_output:type"
            parameter: "input:input:input"
            output: "output:output"
            category: "conform"
            label_key: "file_paths"
