conform:
  thumbnail: "conform.svg"
  steps:
    setup:
      lavel: "Setup"
      index: 50
      commands:
        select_conform_type:
          label: "Select conform type"
          definition_path: "silex_client.commands.select_conform.SelectConform"
          tooltip: "Select the type of conform you want to make"
          inputs:
            find_sequence:
              value: false
            auto_select_type:
              value: true

        append_conform_actions:
          label: "Append conform actions"
          definition_path: "silex_client.commands.iterate_action.IterateAction"
          tooltip: "Append the selected conform actions"
          inputs:
            iterations:
              value: !connect "setup:select_conform_type:types"
            names:
              value: !connect "setup:select_conform_type:types"
            labels:
              value: !connect "setup:select_conform_type:files"
            categories:
              values: "conform"
