publish:
  steps:
    setup:
      lavel: "Setup"
      index: 50
      commands:
        get_publish_output:
          label: "Select publish type"
          path: "silex_client.commands.select_publish.SelectPublish"
          tooltip: "Select the type of publish you want to make"
          ask_user: true
        build_output_path:
          label: "Build output path"
          path: "silex_client.commands.build_output_path.BuildOutputPath"
          tooltip: "Build the complete output path"
          ask_user: True
          parameters:
            output_type: !command-output "setup:get_publish_output"
            use_current_context:
              value: true
              hide: true
            task:
              value: null
              hide: true
            name: "main"
