pull:
  thumbnail: "publish.svg"
  steps:
    pull:
      lavel: "Move publish into work"
      index: 50
      commands:
        select_pull:
          label: "Do you want to pull the publish"
          path: "silex_client.commands.select_pull.SelectPull"
          ask_user: true
        move:
          label: "Move"
          path: "silex_client.commands.move.Move"
          parameters:
            output_type: 
              value: !command-output "setup:get_publish_type:publish_type"
              hide: true
            use_current_context:
              value: true
              hide: true
            task:
              hide: true
            frame_set:
              hide: true
            name:
              value: "main"
              label: "Publish name"
