tester:
  steps:
    setup:
      label: "Setup"
      commands:
        get_input:
          label: "Get input"
          path: "silex_client.commands.tester_get_input.InputTester"
          ask_user: true
          parameters:
            message: "message"

        submit_to_deadline:
          label: "Submit to deadline"
          path: "silex_client.commands.farm.submit_to_deadline.SubmitToDeadlineCommand"
          parameters:
            message: 
              value: !command-output "setup:get_input:message"