publish:
  pre_action:
    - name: "initalize_action"
      command: "print"
      args:
        - "Starting action session"

  post_action:
    - name: "close_action"
      command: "print"
      args:
        - "Closing session"
