publish: !inherit
  parent: "./default.yml"
  key: "publish"

  pre_action:
    commands:
      - name: "get_publish_files"
        path: "silex_client.file.prompt_file"
        tooltip: "Insert the file you want to publish. For a file sequence use # as variable name for frame index"

  action:
    commands:
      - name: "save_current"
        path: "silex_client.action.save"
      - name: "quality_check"
        path: "silex_client.action.quality_check"
      - name: "publish_file"
        path: "silex_client.file.publish_file"
