publish:
  steps:
    action:
      commands:
        get_publish_output:
          label: "Select publish type"
          path: "silex_client.commands.publish.SelectPublish"
          tooltip: "Select the type of publish you want to make"
          ask_user: true
