publish: !inherit
  parent: "./default.yml"
  key: "publish"

  steps: &steps

    action:
      commands:

        publish_file:
          path: "silex_client.commands.file.PublishFile"
          tooltip: "Insert the file you want to publish. For a file sequence use # as variable name for frame index"
          ask_user: false

  tasks:
    modeling:
      steps:

        action:
          commands:
                
            publish_file:
              path: "silex_client.commands.file.PublishFile"
              tooltip: "Insert the file you want to publish. For a file sequence use # as variable name for frame index"
              ask_user: true
