nuke:
  label: "Submit nuke script"
  steps:
    submit_job:
      label: "Setup render parameters"
      index: 20
      commands:
        build_nuke_tasks:
          path: "silex_client.commands.farm.nuke_render_tasks.NukeRenderTasksCommand"
          label: "Nuke Job parameters"
          ask_user: true
          parameters:
            frame_range:
              value: "1001-1050x1"

        submit_to_deadline:
          label: "Submit"
          path: "silex_client.commands.farm.submit_to_deadline.SubmitToDeadlineCommand"
          ask_user: true
          parameters:
            #jobs:
            #  value: !command_output "submit_job:build_nuke_tasks:jobs"
              #value: "test"
            #job_title:
            #  value: !command-output "submit_job:build_nuke_tasks:file_name"
            jobs:
              value: !command-output "submit_job:build_nuke_tasks:tasks"
