save:
  action:
    - command: "dcc.mayalib.file.save"

open:
  action:
    - command: "dcc.mayalib.file.open"

publish:
  rig:
    action:
      - command: "dcc.mayalib.export.scene"
        publish: true
  animation:
    action:
      - command: "dcc.mayalib.utils.playblast"
        publish: true
      - command: "dcc.mayalib.export.animation"
        publish: true
  modeling:
    action:
      - command: "dcc.mayalib.utils.turntable"
        publish: true
      - command: "dcc.mayalib.export.geometry"
        publish: true
  surfacing:
    action:
      - command: "dcc.mayalib.render.submit"
        publish: true
      - command: "dcc.mayalib.export.scene"
        publish: true
