reference_bundle: !inherit
  parent: ".bundle"
  category: "action"

  steps:
    setup:
      lavel: "Setup"
      index: 50
      commands:
        get_bundle_output:
          label: "Select bundle type"
          path: "silex_client.commands.select_bundle_reference.SelectBundleReference"
          parameters:
            find_sequence:
              value: false
