vrscene:
  steps:
    input:
      index: 10
      hide: True
      commands:
        input:
          path: "silex_client.commands.pass.Pass"

    bundle:
      label: "Get ass bundle location"
      index: 15
      commands:
        build_bundle_path:
          label: "Build path"
          path: "silex_client.commands.build_bundle_path.BuildBundlePath"
          parameters:
            file_to_bundle:
              value: !command-output "input:input:file_paths"
            frame_set:
              value: !command-output "input:input:frame_set"
            padding:
              value: !command-output "input:input:padding"
            is_reference:
              value: !command-output "input:input:is_reference"
            output_type:
              value: "vrscene"

    bundle_references:
      label: "Conform vray scene's references"
      index: 20
      commands:
        step_exit:
          label: "Skip reconform"
          path: "silex_client.commands.exit_step.ExitStep"
          parameters:
            enable: !command-output "get_conform_location:get_output_cache:value"
          hide: true

        get_vrscene_references:
          label: "Get referenced files"
          path: "silex_client.commands.get_vrscene_references.GetVrsceneReferences"
          parameters:
            vrscene_files: !command-output "input:input:file_paths"
        bundle_references:
          label: "Conform references found"
          path: "silex_client.commands.iterate_action.IterateAction"
          parameters:
            values:
              value: !command-output "bundle_references:get_vrscene_references:references"
              hide: true
            actions:
              - "conform"
            categories:
              - "action"
            parameter: "setup:get_conform_output:file_paths"
            label_key: "references"
            output: "setup:append_conform_actions"

    bundle_vrscene:
      label: "Conform vray scene"
      index: 30
      commands:
        step_exit:
          label: "Skip reconform"
          path: "silex_client.commands.exit_step.ExitStep"
          parameters:
            enable: !command-output "get_conform_location:get_output_cache:value"
          hide: true

        expand_paths:
          label: "Expand environement variables"
          path: "silex_client.commands.expand_paths.ExpandPaths"
          parameters:
            paths_to_expand:
              value: !command-output "bundle:build_bundle_path:full_path"
              hide: true

        set_vrscene_references:
          label: "Repath attributes"
          path: "silex_client.commands.set_vrscene_references.SetVrsceneReferences"
          tooltip: "Set the new path on the attributes"
          parameters:
            plugins_attributes:
              value: !command-output "bundle_references:get_vrscene_references:plugins"
              hide: true
            reference_values:
              value: !command-output "bundle_references:bundle_references"
              hide: true
            vrscene_src:
              value: !command-output "input:input:file_paths"
              hide: true
            vrscene_dst:
              value: !command-output "bundle_vrscene:expand_paths:expanded_paths"
              hide: true

        set_env:
          label: "Replace path by environement variables"
          path: "silex_client.commands.set_env.SetEnv"
          parameters:
            paths:
              value: !command-output "bundle_vrscene:set_vrscene_references"
            envs:
              value: !command-output "bundle_vrscene:expand_paths:envs"

    output:
      index: 40
      hide: true
      commands:
        output:
          path: "silex_client.commands.pass.Pass"
          parameters:
            input: !command-output "bundle_vrscene:set_env:expanded_paths"
