maya:
  save:
    default:
      - pre:
        - ""
      - action:
        - ""
      - post:
        - ""

    anim:
      - ""

    rig:
      - ""

    fx:
      - ""

    compositing:
      - ""
