name: Conform

on:
  push:
    branches: [ dev, beta, prod ]
  pull_request:
    branches: [ dev, beta, prod ]

  workflow_dispatch:

jobs:
  conform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: pipenv install --deploy --dev

      - name: Run linter
        run: pipenv run lint

      - name: Run formatter
        run: pipenv run format 1>/dev/null

      - name: Commit conform
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply conform chages
          branch: ${{ github.head_ref }}

