name: Format

on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
  types: [closed]

jobs:
  conform:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Black
        run: python -m pip install black

      - name: Install Isort
        run: python -m pip install isort

      - name: Run formatter
        run: black .

      - name: Run import formatter
        run: isort --profile black .

      - name: Commit changes
        run: |
          git config --local user.email "silex@noreply.com"
          git config --local user.name "silex"
          git add --all
          git commit -a -m "[Github Action] Apply auto conform" --allow-empty
          git push
