name: Unit Test

on:
  workflow_dispatch:
  push:
    branches: [ dev, beta, prod ]
  pull_request:
    branches: [ dev, beta, prod ]

jobs:
  unittest-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Cache rez packages
        id: cache-rez
        uses: actions/cache@v2
        with:
          path: c:/users/runneradmin/rez/
          key: ${{ runner.os }}-silex_client

      - name: Install rez
        #if: steps.cache-rez.outputs.cache-hit != 'true'
        run: powershell ./script/install_rez.ps1

      - name: Setup rez
        if: steps.cache-rez.outputs.cache-hit == 'true'
        run: Add-Content $env:GITHUB_PATH "c:/users/runneradmin/rez/"
        shell: powershell

      - run: Add-Content $env:GITHUB_PATH "c:/users/runneradmin/rez/"
        shell: powershell
      - run: $env:PATH
        shell: powershell
      - run: ls "c:/users/runneradmin/rez/"
        shell: powershell
      - run: ls "c:/users/runneradmin"
        shell: powershell
      - run: $env:HOME
        shell: powershell

      - name: Install silex_client
        run: rez build --install

      - name: Test silex_client
        run: rez test silex_client
