name: Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - beta
      - prod
  pull_request:
    branches:
      - dev
      - beta
      - prod
  
jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          architecture: x64

      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-cache

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        if: steps.cache-pip.outputs.cache-hit != 'true'

      - name: Install silex_client
        run: pip install -e .[dev]
        if: steps.cache-pip.outputs.cache-hit != 'true'

      - name: Run unit tests
        run: python -m pytest .
