name: Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - beta
      - prod
  pull_request:
    branches:
      - dev
      - beta
      - prod
  
jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
 

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install silex_client
        run: pip install .[dev]

      - name: Run unit tests
        run: python -m pytest .
