name: Unit Test

on:
  workflow_dispatch:

jobs:
  unittest-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install rez
        run: powershell ./script/install_rez.ps1

      - name: Install silex_client
        run: rez-build --install

      - name: Test silex_client
        run: rez-test silex_client
